### ISSUE TITLE
bug in root code primoprogetto.js

### ISSUE THREAD

**Issue by timkock** [filippogallizia/firstprojectever#2]
```bash
/firstprojectever/primoprogetto.js:7
fratelli : "giovanni"
^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by timkock** [comment]
you are not supposed to commit code to master with bugs ;)

**Comment by filippogallizia** [comment]
ahhaah sorry !
